[package]
name = "imghash-rs"
version = "0.1.0"

description = "A simple image hashing library for Rust"
readme = "README.md"
authors = ["Yannick Alexander"]

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
